[package]
name = "hacam-lib-rs"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR BSD-2-Clause"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
futures = "0.3.31"
thiserror = "2.0.16"
nusb = "0.1.13"
chrono = "0.4.41"
log = "0.4.27"
rand = "0.9.2"
int-enum = "1.2.0"